version: "3.8"
services:
  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
  worker:
    build:
      context: ./docker
      dockerfile: Dockerfile.worker
    command: ["sleep","infinity"]